# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerSvgImagePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_filer_svg_filersvgimagepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('alt_text', models.CharField(max_length=255, verbose_name='alt text')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('file', filer.fields.file.FilerFileField(help_text='Provide an SVG file', on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='SVG file')),
            ],
            options={
                'verbose_name': 'SVG image',
                'verbose_name_plural': 'SVG images',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
