# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0007_auto_20161016_1055'),
        ('cmsplugin_filer_svg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerSvgInlinePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_filer_svg_filersvginlinepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('file', filer.fields.file.FilerFileField(help_text='Provide an SVG file', on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='SVG file')),
            ],
            options={
                'verbose_name': 'Inline SVG image',
                'verbose_name_plural': 'Inline SVG images',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
