# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 16:46
from __future__ import unicode_literals

import cms.models.fields
import ripiu.cmsplugin_filer_svg.models.fields

import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        ('cmsplugin_filer_svg', '0004_auto_20180327_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVG',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filer.File')),
            ],
            # options={
            #     'manager_inheritance_from_future': True,
            # },
            bases=('filer.file',),
        ),
        migrations.AlterField(
            model_name='filersvgimagepluginmodel',
            name='file',
            field=ripiu.cmsplugin_filer_svg.models.fields.FilerSVGField(help_text='Provide an SVG file', on_delete=django.db.models.deletion.CASCADE, to='cmsplugin_filer_svg.SVG', verbose_name='SVG file'),
        ),
        migrations.AlterField(
            model_name='filersvgimagepluginmodel',
            name='link_page',
            field=cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Internal URL'),
        ),
        migrations.AlterField(
            model_name='filersvginlinepluginmodel',
            name='file',
            field=ripiu.cmsplugin_filer_svg.models.fields.FilerSVGField(help_text='Provide an SVG file', on_delete=django.db.models.deletion.CASCADE, to='cmsplugin_filer_svg.SVG', verbose_name='SVG file'),
        ),
    ]
