# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_svg', '0005_auto_20181127_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svg',
            options={'verbose_name': 'SVG file', 'verbose_name_plural': 'SVG files'},
        ),
    ]
